[package]
name = "studyspace"
version = "0.1.0"
description = "Studyspace desktop study app"
authors = []
license = ""
repository = ""
edition = "2024"
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "studyspace_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.0", features = [] }

[dependencies]
tauri = { version = "2.12.0", features = [] }
